name: HCL OneTest Performance

on: workflow_dispatch

jobs:
    Performance-Action:
        name: HCL OneTest Performance GitHub Action-Test
        runs-on: self-hosted
        steps:
         - name: HCL OneTest Performance GitHub Action-Test
           uses: LekyaS/onetest-perf-action-test@tag1
           with:
            workspace: D:\Workspace-2024\
            project: PerfTest
            suite: perftest
